name: xdggs
channels:
  - conda-forge
dependencies:
  - xarray
  - h5netcdf
  - netcdf4
  - pooch
  - matplotlib-base
  - shapely
  - pytest
  - hypothesis
  - ruff
  - typing-extensions
  - geoarrow-pyarrow
  - lonboard
  - arro3-core
  - cdshealpix
  - h3ronpy
